export default function PrivacyPolicyPage() {
  return (
    <main className="mx-auto w-full max-w-[1440px] border-x border-zinc-800 px-6 py-28 md:px-12 bg-black min-h-screen text-zinc-300 font-sans">
      <div className="max-w-4xl mx-auto space-y-12">
        <div>
          <div className="border border-zinc-800 bg-zinc-900 py-1 px-4 text-xs font-mono text-zinc-400 w-max mb-6">SYS_DOC // PRIVACY_POLICY</div>
          <h1 className="text-4xl md:text-5xl font-bold tracking-tight text-white mb-6">DeepNerd Privacy Policy</h1>
          <p className="text-lg text-zinc-400">
            Effective Date: May 3, 2026
          </p>
        </div>

        <section className="space-y-4">
          <h2 className="text-2xl font-bold text-white">1. Introduction & Scope</h2>
          <p>
            This Privacy Policy explains how DeepNerd ("we," "us," or "our") collects, uses, discloses, and safeguards personal data when you use the DeepNerd platform, including Vault Vault IDE, Muac Agent, our APIs, and associated developer ecosystems (collectively, the "Services").
          </p>
          <p>
            <strong>Consumer vs. Commercial Services:</strong> This policy applies to personal data we collect as a "data controller." When we process data on behalf of Enterprise customers through our Commercial Services (such as Dedicated APIs or customized Enterprise Agents), we act as a "data processor," and such processing is governed by our Enterprise Data Processing Agreement (DPA) rather than this generalized policy.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-bold text-white">2. Information We Collect</h2>
          <p>We collect information you provide directly, information collected automatically, and information from third parties.</p>
          <h3 className="text-lg font-semibold text-zinc-100 mt-4">A. Identity, Account, and Payment Data</h3>
          <ul className="list-disc list-inside space-y-1 text-zinc-400 ml-4">
            <li><strong>Profile Information:</strong> Name, email address, company name, developer profile URLs (e.g., GitHub, GitLab).</li>
            <li><strong>Credentials:</strong> Passwords, SSO tokens, and multi-factor authentication data.</li>
            <li><strong>Payment Information:</strong> Billing address, transaction history, and partial credit card data. Full payment information is processed securely by our PCI-compliant payment partners (e.g., Stripe).</li>
          </ul>

          <h3 className="text-lg font-semibold text-zinc-100 mt-4">B. Inputs, Outputs, and AI Interactions</h3>
          <ul className="list-disc list-inside space-y-1 text-zinc-400 ml-4">
            <li><strong>Prompts and Queries:</strong> Text, code, and documents submitted to our models and agents.</li>
            <li><strong>Outputs:</strong> The code, text, or actions generated by our models in response to your Inputs.</li>
            <li><strong>Feedback:</strong> Thumbs up/down, context corrections, and debugging annotations you provide.</li>
          </ul>

          <h3 className="text-lg font-semibold text-zinc-100 mt-4">C. Developer and Integration Data</h3>
          <ul className="list-disc list-inside space-y-1 text-zinc-400 ml-4">
            <li><strong>Codebases:</strong> If you connect repositories to Vault Vault IDE or Muac Agent, we process code snippets necessary for the service.</li>
            <li><strong>API Telemetry:</strong> Request volumes, latency, error rates, and endpoint utilization.</li>
            <li><strong>Agent Action Logs:</strong> Sequences of actions taken by Muac Agent (e.g., terminal commands executed, files modified).</li>
          </ul>

          <h3 className="text-lg font-semibold text-zinc-100 mt-4">D. Technical and Device Data</h3>
          <ul className="list-disc list-inside space-y-1 text-zinc-400 ml-4">
            <li><strong>Log Data:</strong> IP addresses, browser types, Vault IDE versions, application state, and crash diagnostics.</li>
            <li><strong>Cookies & Tracking:</strong> Unique session identifiers and performance tracking cookies to ensure session stability.</li>
          </ul>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-bold text-white">3. Model Training & Data Sources</h2>
          <p>
            DeepNerd trains underlying foundational models and specialized coding agents using a mixture of proprietary datasets, publicly available information, and licensed data.
          </p>
          <ul className="list-disc list-inside space-y-1 text-zinc-400 ml-4">
            <li><strong>Opt-Out for Consumer Users:</strong> By default, data submitted through consumer APIs and standard UI interfaces may be used to improve our models. Users can opt out of data training at any time via their Account Settings.</li>
            <li><strong>Zero-Training for Commercial Services:</strong> We <strong>do not</strong> use Inputs, Outputs, or Developer Data submitted to our Enterprise tiers, Zero-Data Retention endpoints, or Dedicated Muac Agents to train our foundational base models.</li>
          </ul>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-bold text-white">4. How We Use Information</h2>
          <ul className="list-disc list-inside space-y-1 text-zinc-400 ml-4">
            <li><strong>To Provide Services:</strong> Authenticating users, executing code, running AI predictions, and orchestrating Muac Agent workflows.</li>
            <li><strong>To Improve AI Systems:</strong> Fine-tuning models for better coding accuracy, lower latency, and reduced hallucination rates (subject to opt-out rights).</li>
            <li><strong>For Infrastructure & Security:</strong> Detecting abuse, debugging crashes, enforcing rate limits, and securing our API perimeters from malicious automated attacks.</li>
            <li><strong>For Communication:</strong> Sending billing updates, system lifecycle notifications, and API deprecation warnings.</li>
          </ul>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-bold text-white">5. Data Sharing and Disclosures</h2>
          <p>We do not sell your personal data. We only share information under the following circumstances:</p>
          <ul className="list-disc list-inside space-y-1 text-zinc-400 ml-4">
            <li><strong>Infrastructure Providers:</strong> Cloud hosting (e.g., AWS, GCP), database providers, and compute clusters necessary to host our models.</li>
            <li><strong>Enterprise Workspaces:</strong> If you use DeepNerd under an organization's workspace, your activity (logs, code inputs) is visible to the workspace administrators.</li>
            <li><strong>Legal & Safety Requirements:</strong> We may disclose data if legally required (e.g., subpoenas, warrants) or to prevent imminent physical harm, illegal acts, or gross violations of our Usage Policy.</li>
          </ul>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-bold text-white">6. Data Retention & Security</h2>
          <p>
            We implement SOC 2 and ISO 27001 aligned security measures, including TLS 1.3 transit encryption, AES-256 at-rest encryption, and tightly controlled role-based access to databases.
          </p>
          <p>
            We retain data as long as your account is active or as needed to provide our services. You may request account deletion at any time, which initiates a cascade deletion of your personal data within 30 days, except for anonymized telemetry required for financial compliance mapping.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-bold text-white">7. Your Rights and Choices</h2>
          <p>Depending on your jurisdiction, you have the following rights regarding your personal data:</p>
          <ul className="list-disc list-inside space-y-1 text-zinc-400 ml-4">
            <li><strong>Access & Portability:</strong> Request a local export of your personal data and prompt history.</li>
            <li><strong>Correction & Deletion:</strong> Amend inaccurate data or request total erasure of your account.</li>
            <li><strong>Opt-Out of Training:</strong> Prohibit your inputs/outputs from being used to train DeepNerd models.</li>
          </ul>
          <p>To exercise these rights, navigate to your Account Settings or contact <a className="text-white underline hover:no-underline" href="mailto:privacy@deepnerd.io">privacy@deepnerd.io</a>.</p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-bold text-white">8. Legal Bases for Processing (EEA/UK/Swiss Users)</h2>
          <div className="overflow-x-auto mt-4">
            <table className="w-full text-left border-collapse">
              <thead>
                <tr className="border-b border-zinc-800 text-white">
                  <th className="py-2 pr-4">Processing Activity</th>
                  <th className="py-2 pr-4">Legal Basis</th>
                </tr>
              </thead>
              <tbody className="text-zinc-400 text-sm">
                <tr className="border-b border-zinc-800">
                  <td className="py-3 pr-4">Providing the Services (API, Vault IDE execution)</td>
                  <td className="py-3 pr-4">Performance of a Contract</td>
                </tr>
                <tr className="border-b border-zinc-800">
                  <td className="py-3 pr-4">Billing and Account Administration</td>
                  <td className="py-3 pr-4">Performance of a Contract / Legal Obligation</td>
                </tr>
                <tr className="border-b border-zinc-800">
                  <td className="py-3 pr-4">Model Training and AI Improvement</td>
                  <td className="py-3 pr-4">Legitimate Interests (with Opt-Out rights)</td>
                </tr>
                <tr>
                  <td className="py-3 pr-4">Security, Debugging, and Fraud Prevention</td>
                  <td className="py-3 pr-4">Legitimate Interests / Legal Obligation</td>
                </tr>
              </tbody>
            </table>
          </div>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-bold text-white">9. International Data Transfers</h2>
          <p>
            DeepNerd operates globally. Data may be processed in the United States and other jurisdictions. We utilize Standard Contractual Clauses (SCCs) and comply with the EU-U.S. Data Privacy Framework where applicable to ensure lawful cross-border transfers.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-bold text-white">10. Children's Privacy</h2>
          <p>
            Our Services are intended for developers, researchers, and enterprises. We do not knowingly collect personal data from individuals under the age of 18. If we identify that a minor has provisioned an account, we will immediately terminate the account and purge the data.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-bold text-white">11. Changes to this Policy</h2>
          <p>
            We may update this Privacy Policy to reflect infrastructure updates, legal requirements, or new features. We will notify you of material changes via email or an in-app banner 30 days prior to enforcement.
          </p>
        </section>

        <div className="pt-12 border-t border-zinc-800">
          <p className="text-sm font-mono text-zinc-500 text-center">
            END OF FILE // DEEPNERD_PRIVACY_POLICY
          </p>
        </div>
      </div>
    </main>
  );
}
